# Generated by Django 5.1.3 on 2025-06-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_foods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
    ]
