# Generated by Django 5.1.3 on 2025-06-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_reps', models.IntegerField()),
                ('max_reps', models.IntegerField()),
                ('workout_ratio_numerator', models.IntegerField()),
                ('workout_ratio_denominator', models.IntegerField()),
                ('min_rest', models.IntegerField()),
                ('max_rest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_individual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('muscles', models.ManyToManyField(to='workout.musclegroup')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='workout.workouttype')),
            ],
            options={
                'unique_together': {('name', 'workout_type')},
            },
        ),
    ]
