export const foods = [
  // Protein Sources
  {
    id: 1,
    name: "Grilled Chicken Breast",
    category: "Protein",
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    serving_size_grams: 100,
  },
  {
    id: 2,
    name: "Grilled Salmon",
    category: "Protein",
    calories: 206,
    protein: 22,
    carbs: 0,
    fats: 12,
    serving_size_grams: 100,
  },
  {
    id: 3,
    name: "Boiled Egg (Large)",
    category: "Protein",
    calories: 78,
    protein: 6,
    carbs: 0.6,
    fats: 5,
    serving_size_grams: 50,
  },
  {
    id: 4,
    name: "Greek Yogurt",
    category: "Protein",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fats: 0.4,
    serving_size_grams: 100,
  },
  {
    id: 5,
    name: "Cooked Lentils",
    category: "Protein",
    calories: 116,
    protein: 9,
    carbs: 20,
    fats: 0.4,
    serving_size_grams: 100,
  },
  {
    id: 6,
    name: "Cottage Cheese",
    category: "Protein",
    calories: 98,
    protein: 11,
    carbs: 3.4,
    fats: 4.3,
    serving_size_grams: 100,
  },
  {
    id: 7,
    name: "Tuna (canned in water)",
    category: "Protein",
    calories: 116,
    protein: 26,
    carbs: 0,
    fats: 1,
    serving_size_grams: 100,
  },

  // Carbohydrate Sources
  {
    id: 10,
    name: "Cooked White Rice",
    category: "Carbohydrate",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
    serving_size_grams: 100,
  },
  {
    id: 11,
    name: "Cooked Brown Rice",
    category: "Carbohydrate",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fats: 0.9,
    serving_size_grams: 100,
  },
  {
    id: 12,
    name: "Roasted Sweet Potato",
    category: "Carbohydrate",
    calories: 90,
    protein: 2,
    carbs: 21,
    fats: 0.1,
    serving_size_grams: 100,
  },
  {
    id: 13,
    name: "Oats (dry)",
    category: "Carbohydrate",
    calories: 389,
    protein: 17,
    carbs: 66,
    fats: 7,
    serving_size_grams: 100,
  },
  {
    id: 14,
    name: "Whole Wheat Bread (1 slice)",
    category: "Carbohydrate",
    calories: 82,
    protein: 3,
    carbs: 14,
    fats: 1,
    serving_size_grams: 30,
  },
  {
    id: 15,
    name: "Cooked Quinoa",
    category: "Carbohydrate",
    calories: 120,
    protein: 4.1,
    carbs: 21,
    fats: 1.9,
    serving_size_grams: 100,
  },

  // Healthy Fat Sources
  {
    id: 20,
    name: "Avocado",
    category: "Fat",
    calories: 160,
    protein: 2,
    carbs: 9,
    fats: 15,
    serving_size_grams: 100,
  },
  {
    id: 21,
    name: "Almonds (handful)",
    category: "Fat",
    calories: 164,
    protein: 6,
    carbs: 6,
    fats: 14,
    serving_size_grams: 28,
  },
  {
    id: 22,
    name: "Olive Oil (1 tbsp)",
    category: "Fat",
    calories: 119,
    protein: 0,
    carbs: 0,
    fats: 14,
    serving_size_grams: 14,
  },

  // Vegetables
  {
    id: 30,
    name: "Cooked Broccoli",
    category: "Vegetable",
    calories: 35,
    protein: 2.4,
    carbs: 7,
    fats: 0.4,
    serving_size_grams: 100,
  },
  {
    id: 31,
    name: "Fresh Spinach",
    category: "Vegetable",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fats: 0.4,
    serving_size_grams: 100,
  },
  {
    id: 32,
    name: "Mixed Green Salad",
    category: "Vegetable",
    calories: 15,
    protein: 1,
    carbs: 3,
    fats: 0.2,
    serving_size_grams: 100,
  },

  // Fruits
  {
    id: 40,
    name: "Banana (medium)",
    category: "Fruit",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.4,
    serving_size_grams: 118,
  },
  {
    id: 41,
    name: "Apple (medium)",
    category: "Fruit",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fats: 0.3,
    serving_size_grams: 182,
  },
  {
    id: 42,
    name: "Mixed Berries",
    category: "Fruit",
    calories: 50,
    protein: 1,
    carbs: 12,
    fats: 0.5,
    serving_size_grams: 100,
  },
];
