# Generated by Django 5.1.3 on 2025-06-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('exercise_type', models.CharField(choices=[('compound', 'مركب (Compound)'), ('accessory', 'إضافي (Accessory)')], max_length=50)),
                ('unit', models.CharField(choices=[('reps', 'تكرارات (Reps)'), ('duration', 'مدة (Duration)')], max_length=50)),
                ('description', models.TextField()),
                ('environment', models.CharField(choices=[('gym', 'نادي رياضي (Gym)'), ('home', 'منزل (Home)'), ('gymhome', 'نادي/منزل (Gym & Home)')], max_length=50)),
                ('level_str', models.CharField(blank=True, default='', max_length=255)),
                ('equipment', models.ManyToManyField(blank=True, to='exercise.equipment')),
                ('substitutes', models.ManyToManyField(blank=True, to='exercise.exercise')),
                ('muscles', models.ManyToManyField(related_name='exercises', to='exercise.musclegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='exercise.exercise')),
            ],
            options={
                'unique_together': {('exercise', 'name')},
            },
        ),
    ]
